<?php

include_once "./Decorator.php";
class ConcreteDecoratorA extends Decorator{


    private $addedState;

    public function operation()
    {
        $this->component->operation(); // TODO: Change the autogenerated stub
        $this->addedState = "concreteDecoratorA state";
        echo $this->addedState."\n";
        echo "具体装饰对象A的操作\n";
    }
}