<?php


include_once("./Decorator.php");
class ConcreteDecoratorB extends Decorator{


    public function operation()
    {
        $this->component->operation(); // TODO: Change the autogenerated stub

        $this->addBehavior();
    }

    private function addBehavior(){
    	echo "具体对象b 操作\n";
        echo "ConcreteDecoratorB Status.\n";

    }
}