<?php


include_once "TestPaper.php";

class TestPaperB extends TestPaper{

    public function answer1()
    {
        return "c"; // TODO: Change the autogenerated stub
    }

    public function answer2()
    {
        return "d"; // TODO: Change the autogenerated stub
    }
}